include:
  - board: nrfmicro/nrf52833/zmk
    shield: migpad
    snippet: studio-rpc-usb-uart
    cmake-args: 
        -DCONFIG_ZMK_STUDIO=y 
        -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nrfmicro/nrf52833/zmk
    shield: settings_reset
